### ISSUE TITLE
1.17 Migration

### ISSUE THREAD

**Issue by ErikDombi** [Age-of-PVP/VRP-Core#1]
Leaving a checklist of things that need to be patched for 1.17 update

**Comment by ErikDombi** [comment]
- [ ] Fix compatibility with MVdwPlaceholderAPI.

Issue likely stems from the dependency itself.

Check for updates from both the [Github](https://github.com/Maximvdw/MVdWPlaceholderAPI) and [Jenkins ](https://ci.mvdw-software.com/job/MVdWPlaceholderAPI/)Pages

```
[03:09:09] [Server thread/INFO]: [MVdW] VRP-Core added custom placeholder {wantedstring}
[03:09:09] [Server thread/ERROR]: Error occurred while enabling VRP-Core v0.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "be.maximvdw.placeholderapi.internal.PlaceholderPack.addOfflinePlaceholder(String, String, boolean, be.maximvdw.placeholderapi.internal.PlaceholderReplacer)" because "be.maximvdw.placeholderapi.PlaceholderAPI.customPlaceholders" is null
        at be.maximvdw.placeholderapi.PlaceholderAPI.registerPlaceholder(PlaceholderAPI.java:112) ~[?:?]
        at VRPCore.VRPCore.onEnable(VRPCore.java:78) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
[VRPCore.VRPCore.onEnable(VRPCore.java:78) ~[?:?]](https://github.com/Age-of-PVP/VRP-Core/blob/main/VRP-Core/src/main/java/VRPCore/VRPCore.java#L78)

**Comment by ErikDombi** [comment]
- [ ] Fix compatibility with Vault

Issue likely stems from [VRPCore.VRPCore.onEnable(VRPCore.java:156) ~[?:?]](https://github.com/Age-of-PVP/VRP-Core/blob/f443b6ae301cb0ea00cffbba4957fe0f7186d76e/VRP-Core/src/main/java/VRPCore/VRPCore.java#L156)

Links of interest
[Vault Github](https://github.com/MilkBowl/Vault)
[VaultAPI Github](https://github.com/MilkBowl/VaultAPI)

**Comment by ErikDombi** [comment]
- [ ] Fix compatibility with PlaceholderAPI

Again another issue with a likely outdated dependency. 

```
[03:36:49] [Server thread/ERROR]: Error occurred while enabling VRP-Core v0.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.clip.placeholderapi.PlaceholderAPIPlugin.getLocalExpansionManager()" because the return value of "me.clip.placeholderapi.expansion.PlaceholderExpansion.getPlaceholderAPI()" is null
        at me.clip.placeholderapi.expansion.PlaceholderExpansion.register(PlaceholderExpansion.java:132) ~[?:?]
        at VRPCore.VRPCore.onEnable(VRPCore.java:117) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62) ~[?:?]
        at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:764) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1944) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1783) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1764) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1102) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
[VRPCore.VRPCore.onEnable(VRPCore.java:117) ~[?:?]](https://github.com/Age-of-PVP/VRP-Core/blob/f443b6ae301cb0ea00cffbba4957fe0f7186d76e/VRP-Core/src/main/java/VRPCore/VRPCore.java#L117)

Once again, keep an eye on [PlaceholderAPI Github](https://github.com/PlaceholderAPI/PlaceholderAPI) and [PlaceholderAPI Jenkins](https://ci.extendedclip.com/job/PlaceholderAPI/)
